# Generated by Django 4.2.1 on 2023-12-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_purchasebill_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='min_stock',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
